"""API 元信息。"""

from __future__ import annotations

from quant_balance.core.factors import list_factor_definitions
from quant_balance.core.strategies import SIGNAL_REGISTRY, STRATEGY_REGISTRY


def build_api_meta() -> dict:
    """返回 API 元信息，包含可用策略和注意事项。"""
    return {
        "strategies": list(STRATEGY_REGISTRY.keys()),
        "signals": list(SIGNAL_REGISTRY.keys()),
        "factors": list_factor_definitions(),
        "defaults": {
            "backtest": {
                "asset_type": "stock",
                "timeframe": "1d",
                "strategy": "sma_cross",
                "cash": 100_000.0,
                "commission": 0.001,
                "slippage_mode": "off",
                "slippage_rate": 0.0,
                "benchmark_symbol": None,
                "benchmark_asset_type": None,
                "data_provider": None,
                "benchmark_data_provider": None,
            },
            "optimize": {
                "asset_type": "stock",
                "strategy": "sma_cross",
                "cash": 100_000.0,
                "commission": 0.001,
                "maximize": "Sharpe Ratio",
                "data_provider": None,
            },
            "screening": {
                "asset_type": "stock",
                "timeframe": "1d",
                "signal": "sma_cross",
                "market_regime": None,
                "market_regime_symbol": "000300.SH",
                "pool_filters": {
                    "industries": [],
                    "exclude_st": False,
                    "min_listing_days": None,
                    "min_market_cap": None,
                    "max_market_cap": None,
                    "min_pe": None,
                    "max_pe": None,
                },
                "top_n": 20,
                "cash": 100_000.0,
                "data_provider": None,
            },
            "stock_pool": {
                "filters": {
                    "industries": [],
                    "exclude_st": False,
                    "min_listing_days": None,
                    "min_market_cap": None,
                    "max_market_cap": None,
                    "min_pe": None,
                    "max_pe": None,
                },
            },
            "factors_rank": {
                "market_regime": None,
                "market_regime_symbol": "000300.SH",
                "factors": [
                    {"name": "roe", "weight": 0.4},
                    {"name": "pe", "weight": 0.25},
                    {"name": "pb", "weight": 0.2},
                    {"name": "dv_ratio", "weight": 0.15},
                ],
                "pool_filters": {
                    "industries": [],
                    "exclude_st": False,
                    "min_listing_days": None,
                    "min_market_cap": None,
                    "max_market_cap": None,
                    "min_pe": None,
                    "max_pe": None,
                },
                "top_n": 50,
            },
            "portfolio": {
                "allocation": "equal",
                "rebalance_frequency": "monthly",
                "cash": 100_000.0,
                "commission": 0.001,
                "data_provider": None,
            },
            "paper": {
                "strategy": "macd",
                "strategy_params": {},
                "symbols": [],
                "initial_cash": 100_000.0,
                "asset_type": "stock",
                "start_date": None,
                "data_provider": None,
            },
            "scheduler": {
                "enabled": False,
                "scan_time": "16:00",
                "strategies": ["macd", "rsi"],
                "symbols_source": "stock_pool",
                "asset_type": "stock",
                "top_n": 20,
                "lookback_days": 365,
                "cash": 100_000.0,
                "data_provider": None,
            },
            "notify": {
                "enabled": [],
                "wecom": {"webhook": ""},
                "dingtalk": {"webhook": "", "secret": ""},
                "serverchan": {"sendkey": ""},
                "email": {
                    "receiver": "",
                    "smtp_host": "",
                    "smtp_port": 465,
                    "sender": "",
                    "password": "",
                    "username": "",
                    "use_ssl": True,
                    "starttls": True,
                },
            },
        },
        "notes": [
            "回测引擎基于 backtesting.py，支持精细化单股回测和参数优化。",
            "批量筛选引擎基于 vectorbt，支持向量化快速扫描多只股票。",
            "market/regime 可返回当前市场状态或区间状态序列，当前至少区分 BULL / BEAR / SIDEWAYS。",
            "历史股票池支持行业、市值、PE、ST、次新等前置过滤，并继续以 get_pool_at_date() 为底座。",
            "多因子打分引擎支持因子标准化、加权总分与排名，可直接用于筛选研究与组合候选池构建。",
            "组合回测基于 vectorbt 目标权重矩阵，适合做多标的轮动、再平衡与收益归因研究。",
            "scheduler.enabled=true 时，服务启动后会自动恢复盘后扫描调度；也可通过 API 手动触发。",
            "signals/today、signals/history 和 signals/{id} 支持信号查询、状态流转与后续表现跟踪。",
            "signals/export 支持把指定日期的信号导出为 CSV、QMT Python 脚本和 JSON。",
            "paper/start、paper/status、paper/pause 和 paper/stop 支持模拟盘会话、持仓估值、交易记录与最终报告。",
            "notify/test 可用来验证企业微信、钉钉、Server酱和 SMTP 邮件渠道连通性。",
            "backtest/run 会自动把单股回测结果写入 SQLite；可通过 backtest/history 与 backtest/compare 查询和对比。",
            "数据默认使用前复权价格（qfq）。",
            "行情数据默认按 akshare -> baostock -> tushare 顺序回退，也可在请求中显式指定。",
            "backtest / optimize / screening 支持 asset_type=convertible_bond；当前可转债仅支持 tushare，并沿用简化版股票化撮合规则。",
            "backtest/run 与 screening/run 支持 timeframe=1d/1min/5min/15min/30min/60min；分钟线当前仅支持 stock + tushare，且返回未复权价格。",
            "factors/rank 与 screening/run 支持可选 market_regime 过滤，默认基于沪深300日线状态判断。",
            "optimize、portfolio、paper、scheduler 仍以日线研究为主，不提供分钟线参数入口。",
            "默认面向本地研究演示，不作为实盘建议。",
        ],
        "server_mode": "api",
    }
