"""回测核心子包。"""

from quant_balance.core.backtest import BacktestResult, optimize, run_backtest
from quant_balance.core.report import (
    bt_trades_to_dicts,
    equity_curve_to_dicts,
    normalize_bt_stats,
    normalize_vbt_stats,
)
from quant_balance.core.screening import ScreeningResult, run_screening
from quant_balance.core.strategies import (
    BollingerBreakout,
    BuyAndHold,
    DcaStrategy,
    EmaCross,
    GridStrategy,
    MacdCross,
    MaRsiFilter,
    RsiStrategy,
    SIGNAL_REGISTRY,
    STRATEGY_REGISTRY,
    SmaCross,
    bollinger_signals,
    dca_signals,
    ema_cross_signals,
    grid_signals,
    macd_signals,
    ma_rsi_filter_signals,
    rsi_signals,
    sma_cross_signals,
)

__all__ = [
    "BacktestResult",
    "BollingerBreakout",
    "BuyAndHold",
    "DcaStrategy",
    "EmaCross",
    "GridStrategy",
    "MacdCross",
    "MaRsiFilter",
    "RsiStrategy",
    "SIGNAL_REGISTRY",
    "STRATEGY_REGISTRY",
    "ScreeningResult",
    "SmaCross",
    "bollinger_signals",
    "bt_trades_to_dicts",
    "dca_signals",
    "ema_cross_signals",
    "equity_curve_to_dicts",
    "grid_signals",
    "macd_signals",
    "ma_rsi_filter_signals",
    "normalize_bt_stats",
    "normalize_vbt_stats",
    "optimize",
    "rsi_signals",
    "run_backtest",
    "run_screening",
    "sma_cross_signals",
]
